name: Build and Extract Caddy

on:
  push:
    branches: [ 'main', 'dev' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t custom-caddy .

    - name: Create container from image
      run: docker create --name caddy-container custom-caddy

    - name: Copy caddy binary from container
      run: docker cp caddy-container:/usr/bin/caddy ./caddy

    - name: Prepare output directory
      run: |
        mkdir -p output
        mv ./caddy output/caddy

    - name: Commit and push caddy binary
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'  # Specify the branch where you want to push the file
        force: true
        directory: 'output'
