name: Build and Extract Caddy

on:
  push:
    branches: [ 'main' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t custom-caddy .

    - name: Create container from image
      run: docker create --name caddy-container custom-caddy

    - name: Copy caddy binary from container
      run: docker cp caddy-container:/usr/bin/caddy ./caddy

    - name: Prepare output directory
      run: |
        chmod +x ./caddy
        version=$(./caddy --version)
        echo ${version}
        declare -a array
        IFS=' ' read -r -a array <<< "$version"
        mkdir -p output
        mv ./caddy output/caddy
        echo "${array[@]}" > "output/${array[0]}"

    - name: Create and push Caddy Binary
      uses: EndBug/add-and-commit@v9
      with:
        add: 'output'
        author_name: GitHub Action
        author_email: action@github.com
        message: 'New xcaddy build'
        new_branch: build
        push: true
        cwd: '.'
        default_author: github_actions
        pathspec_error_handling: ignore
